name: Build, Test and Release

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run tests
      run: cargo test
      working-directory: ./RustTest

    - name: Build the release
      run: cargo build --release
      working-directory: ./RustTest

    - name: Strip the binary
      run: strip ./RustTest/target/release/RustTest

    - name: Upload release asset
      uses: actions/upload-artifact@v2
      with:
        name: linux-release
        path: ./RustTest/target/release/RustTest

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run tests
      run: cargo test
      working-directory: ./RustTest

    - name: Build the release
      run: cargo build --release
      working-directory: ./RustTest

    - name: Strip the binary
      run: strip ./RustTest/target/release/RustTest.exe

    - name: Upload release asset
      uses: actions/upload-artifact@v2
      with:
        name: windows-release
        path: ./RustTest/target/release/RustTest.exe

  create-release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get current date and time
      id: datetime
      run: echo "RELEASE_NAME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ env.RELEASE_NAME }}
        body: |
          Release notes for ${{ env.RELEASE_NAME }}
        draft: false
        prerelease: false

    - name: Download Linux Release
      uses: actions/download-artifact@v2
      with:
        name: linux-release
        path: ./RustTest/target/release

    - name: Upload Linux Binary to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./RustTest/target/release/RustTest
        asset_name: RustTest-linux
        asset_content_type: application/octet-stream

    - name: Download Windows Release
      uses: actions/download-artifact@v2
      with:
        name: windows-release
        path: ./RustTest/target/release

    - name: Upload Windows Binary to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./RustTest/target/release/RustTest.exe
        asset_name: RustTest-windows.exe
        asset_content_type: application/octet-stream
